import 'package:flutter/material.dart';

/// Emoji data class to hold emoji character and name
class EmojiData {
  final String emoji;
  final String name;

  const EmojiData({required this.emoji, required this.name});
}

/// Icon data class to hold icon and name
class IconDataItem {
  final IconData icon;
  final String name;

  const IconDataItem({required this.icon, required this.name});
}

/// Complete list of emojis organized by category
class EmojiList {
  // Smileys & Emotion
  static const List<EmojiData> smileysAndEmotion = [
    EmojiData(emoji: '😀', name: 'Grinning Face'),
    EmojiData(emoji: '😃', name: 'Grinning Face with Big Eyes'),
    EmojiData(emoji: '😄', name: 'Grinning Face with Smiling Eyes'),
    EmojiData(emoji: '😁', name: 'Beaming Face with Smiling Eyes'),
    EmojiData(emoji: '😆', name: 'Grinning Squinting Face'),
    EmojiData(emoji: '😅', name: 'Grinning Face with Sweat'),
    EmojiData(emoji: '🤣', name: 'Rolling on the Floor Laughing'),
    EmojiData(emoji: '😂', name: 'Face with Tears of Joy'),
    EmojiData(emoji: '🙂', name: 'Slightly Smiling Face'),
    EmojiData(emoji: '🙃', name: 'Upside-Down Face'),
    EmojiData(emoji: '🫠', name: 'Melting Face'),
    EmojiData(emoji: '😉', name: 'Winking Face'),
    EmojiData(emoji: '😊', name: 'Smiling Face with Smiling Eyes'),
    EmojiData(emoji: '😇', name: 'Smiling Face with Halo'),
    EmojiData(emoji: '🥰', name: 'Smiling Face with Hearts'),
    EmojiData(emoji: '😍', name: 'Smiling Face with Heart-Eyes'),
    EmojiData(emoji: '🤩', name: 'Star-Struck'),
    EmojiData(emoji: '😘', name: 'Face Blowing a Kiss'),
    EmojiData(emoji: '😗', name: 'Kissing Face'),
    EmojiData(emoji: '😚', name: 'Kissing Face with Closed Eyes'),
    EmojiData(emoji: '😙', name: 'Kissing Face with Smiling Eyes'),
    EmojiData(emoji: '🥲', name: 'Smiling Face with Tear'),
    EmojiData(emoji: '😋', name: 'Face Savoring Food'),
    EmojiData(emoji: '😛', name: 'Face with Tongue'),
    EmojiData(emoji: '😜', name: 'Winking Face with Tongue'),
    EmojiData(emoji: '🤪', name: 'Zany Face'),
    EmojiData(emoji: '😝', name: 'Squinting Face with Tongue'),
    EmojiData(emoji: '🤑', name: 'Money-Mouth Face'),
    EmojiData(emoji: '🤗', name: 'Smiling Face with Open Hands'),
    EmojiData(emoji: '🤭', name: 'Face with Hand Over Mouth'),
    EmojiData(emoji: '🫢', name: 'Face with Open Eyes and Hand Over Mouth'),
    EmojiData(emoji: '🫣', name: 'Face with Peeking Eye'),
    EmojiData(emoji: '🤫', name: 'Shushing Face'),
    EmojiData(emoji: '🤔', name: 'Thinking Face'),
    EmojiData(emoji: '🫡', name: 'Saluting Face'),
    EmojiData(emoji: '🤐', name: 'Zipper-Mouth Face'),
    EmojiData(emoji: '🤨', name: 'Face with Raised Eyebrow'),
    EmojiData(emoji: '😐', name: 'Neutral Face'),
    EmojiData(emoji: '😑', name: 'Expressionless Face'),
    EmojiData(emoji: '😶', name: 'Face Without Mouth'),
    EmojiData(emoji: '🫥', name: 'Dotted Line Face'),
    EmojiData(emoji: '😏', name: 'Smirking Face'),
    EmojiData(emoji: '😒', name: 'Unamused Face'),
    EmojiData(emoji: '🙄', name: 'Face with Rolling Eyes'),
    EmojiData(emoji: '😬', name: 'Grimacing Face'),
    EmojiData(emoji: '🤥', name: 'Lying Face'),
    EmojiData(emoji: '🫨', name: 'Shaking Face'),
    EmojiData(emoji: '😌', name: 'Relieved Face'),
    EmojiData(emoji: '😔', name: 'Pensive Face'),
    EmojiData(emoji: '😪', name: 'Sleepy Face'),
    EmojiData(emoji: '🤤', name: 'Drooling Face'),
    EmojiData(emoji: '😴', name: 'Sleeping Face'),
    EmojiData(emoji: '😷', name: 'Face with Medical Mask'),
    EmojiData(emoji: '🤒', name: 'Face with Thermometer'),
    EmojiData(emoji: '🤕', name: 'Face with Head-Bandage'),
    EmojiData(emoji: '🤢', name: 'Nauseated Face'),
    EmojiData(emoji: '🤮', name: 'Face Vomiting'),
    EmojiData(emoji: '🤧', name: 'Sneezing Face'),
    EmojiData(emoji: '🥵', name: 'Hot Face'),
    EmojiData(emoji: '🥶', name: 'Cold Face'),
    EmojiData(emoji: '🥴', name: 'Woozy Face'),
    EmojiData(emoji: '😵', name: 'Dizzy Face'),
    EmojiData(emoji: '🤯', name: 'Exploding Head'),
    EmojiData(emoji: '🤠', name: 'Cowboy Hat Face'),
    EmojiData(emoji: '🥳', name: 'Partying Face'),
    EmojiData(emoji: '🥸', name: 'Disguised Face'),
    EmojiData(emoji: '😎', name: 'Smiling Face with Sunglasses'),
    EmojiData(emoji: '🤓', name: 'Nerd Face'),
    EmojiData(emoji: '🧐', name: 'Face with Monocle'),
    EmojiData(emoji: '😕', name: 'Confused Face'),
    EmojiData(emoji: '🫤', name: 'Face with Diagonal Mouth'),
    EmojiData(emoji: '😟', name: 'Worried Face'),
    EmojiData(emoji: '🙁', name: 'Slightly Frowning Face'),
    EmojiData(emoji: '😮', name: 'Face with Open Mouth'),
    EmojiData(emoji: '😯', name: 'Hushed Face'),
    EmojiData(emoji: '😲', name: 'Astonished Face'),
    EmojiData(emoji: '😳', name: 'Flushed Face'),
    EmojiData(emoji: '🥺', name: 'Pleading Face'),
    EmojiData(emoji: '🥹', name: 'Face Holding Back Tears'),
    EmojiData(emoji: '😦', name: 'Frowning Face with Open Mouth'),
    EmojiData(emoji: '😧', name: 'Anguished Face'),
    EmojiData(emoji: '😨', name: 'Fearful Face'),
    EmojiData(emoji: '😰', name: 'Anxious Face with Sweat'),
    EmojiData(emoji: '😥', name: 'Sad but Relieved Face'),
    EmojiData(emoji: '😢', name: 'Crying Face'),
    EmojiData(emoji: '😭', name: 'Loudly Crying Face'),
    EmojiData(emoji: '😱', name: 'Face Screaming in Fear'),
    EmojiData(emoji: '😖', name: 'Confounded Face'),
    EmojiData(emoji: '😣', name: 'Persevering Face'),
    EmojiData(emoji: '😞', name: 'Disappointed Face'),
    EmojiData(emoji: '😓', name: 'Downcast Face with Sweat'),
    EmojiData(emoji: '😩', name: 'Weary Face'),
    EmojiData(emoji: '😫', name: 'Tired Face'),
    EmojiData(emoji: '🥱', name: 'Yawning Face'),
    EmojiData(emoji: '😤', name: 'Face with Steam From Nose'),
    EmojiData(emoji: '😡', name: 'Pouting Face'),
    EmojiData(emoji: '😠', name: 'Angry Face'),
    EmojiData(emoji: '🤬', name: 'Face with Symbols on Mouth'),
    EmojiData(emoji: '😈', name: 'Smiling Face with Horns'),
    EmojiData(emoji: '👿', name: 'Angry Face with Horns'),
    EmojiData(emoji: '💀', name: 'Skull'),
    EmojiData(emoji: '💩', name: 'Pile of Poo'),
    EmojiData(emoji: '🤡', name: 'Clown Face'),
    EmojiData(emoji: '👹', name: 'Ogre'),
    EmojiData(emoji: '👺', name: 'Goblin'),
    EmojiData(emoji: '👻', name: 'Ghost'),
    EmojiData(emoji: '👽', name: 'Alien'),
    EmojiData(emoji: '👾', name: 'Alien Monster'),
    EmojiData(emoji: '🤖', name: 'Robot'),
  ];

  // Animals & Nature
  static const List<EmojiData> animalsAndNature = [
    EmojiData(emoji: '🐵', name: 'Monkey Face'),
    EmojiData(emoji: '🐒', name: 'Monkey'),
    EmojiData(emoji: '🦍', name: 'Gorilla'),
    EmojiData(emoji: '🦧', name: 'Orangutan'),
    EmojiData(emoji: '🐶', name: 'Dog Face'),
    EmojiData(emoji: '🐕', name: 'Dog'),
    EmojiData(emoji: '🦮', name: 'Guide Dog'),
    EmojiData(emoji: '🐩', name: 'Poodle'),
    EmojiData(emoji: '🐺', name: 'Wolf'),
    EmojiData(emoji: '🦊', name: 'Fox'),
    EmojiData(emoji: '🦝', name: 'Raccoon'),
    EmojiData(emoji: '🐱', name: 'Cat Face'),
    EmojiData(emoji: '🐈', name: 'Cat'),
    EmojiData(emoji: '🦁', name: 'Lion'),
    EmojiData(emoji: '🐯', name: 'Tiger Face'),
    EmojiData(emoji: '🐅', name: 'Tiger'),
    EmojiData(emoji: '🐆', name: 'Leopard'),
    EmojiData(emoji: '🐴', name: 'Horse Face'),
    EmojiData(emoji: '🐎', name: 'Horse'),
    EmojiData(emoji: '🦄', name: 'Unicorn'),
    EmojiData(emoji: '🦓', name: 'Zebra'),
    EmojiData(emoji: '🦌', name: 'Deer'),
    EmojiData(emoji: '🐮', name: 'Cow Face'),
    EmojiData(emoji: '🐂', name: 'Ox'),
    EmojiData(emoji: '🐃', name: 'Water Buffalo'),
    EmojiData(emoji: '🐄', name: 'Cow'),
    EmojiData(emoji: '🐷', name: 'Pig Face'),
    EmojiData(emoji: '🐖', name: 'Pig'),
    EmojiData(emoji: '🐗', name: 'Boar'),
    EmojiData(emoji: '🐽', name: 'Pig Nose'),
    EmojiData(emoji: '🐏', name: 'Ram'),
    EmojiData(emoji: '🐑', name: 'Ewe'),
    EmojiData(emoji: '🐐', name: 'Goat'),
    EmojiData(emoji: '🐪', name: 'Camel'),
    EmojiData(emoji: '🐫', name: 'Two-Hump Camel'),
    EmojiData(emoji: '🦙', name: 'Llama'),
    EmojiData(emoji: '🦒', name: 'Giraffe'),
    EmojiData(emoji: '🐘', name: 'Elephant'),
    EmojiData(emoji: '🦣', name: 'Mammoth'),
    EmojiData(emoji: '🦏', name: 'Rhinoceros'),
    EmojiData(emoji: '🦛', name: 'Hippopotamus'),
    EmojiData(emoji: '🐭', name: 'Mouse Face'),
    EmojiData(emoji: '🐁', name: 'Mouse'),
    EmojiData(emoji: '🐀', name: 'Rat'),
    EmojiData(emoji: '🐹', name: 'Hamster'),
    EmojiData(emoji: '🐰', name: 'Rabbit Face'),
    EmojiData(emoji: '🐇', name: 'Rabbit'),
    EmojiData(emoji: '🐿️', name: 'Chipmunk'),
    EmojiData(emoji: '🦫', name: 'Beaver'),
    EmojiData(emoji: '🦔', name: 'Hedgehog'),
    EmojiData(emoji: '🦇', name: 'Bat'),
    EmojiData(emoji: '🐻', name: 'Bear'),
    EmojiData(emoji: '🐨', name: 'Koala'),
    EmojiData(emoji: '🐼', name: 'Panda'),
    EmojiData(emoji: '🦥', name: 'Sloth'),
    EmojiData(emoji: '🦦', name: 'Otter'),
    EmojiData(emoji: '🦨', name: 'Skunk'),
    EmojiData(emoji: '🦘', name: 'Kangaroo'),
    EmojiData(emoji: '🦡', name: 'Badger'),
    EmojiData(emoji: '🐾', name: 'Paw Prints'),
  ];

  // Food & Drink
  static const List<EmojiData> foodAndDrink = [
    EmojiData(emoji: '🍄', name: 'Mushroom'),
    EmojiData(emoji: '🍇', name: 'Grapes'),
    EmojiData(emoji: '🍈', name: 'Melon'),
    EmojiData(emoji: '🍉', name: 'Watermelon'),
    EmojiData(emoji: '🍊', name: 'Tangerine'),
    EmojiData(emoji: '🍋', name: 'Lemon'),
    EmojiData(emoji: '🍌', name: 'Banana'),
    EmojiData(emoji: '🍍', name: 'Pineapple'),
    EmojiData(emoji: '🥭', name: 'Mango'),
    EmojiData(emoji: '🍎', name: 'Red Apple'),
    EmojiData(emoji: '🍏', name: 'Green Apple'),
    EmojiData(emoji: '🍐', name: 'Pear'),
    EmojiData(emoji: '🍑', name: 'Peach'),
    EmojiData(emoji: '🍒', name: 'Cherries'),
    EmojiData(emoji: '🍓', name: 'Strawberry'),
    EmojiData(emoji: '🫐', name: 'Blueberries'),
    EmojiData(emoji: '🥝', name: 'Kiwi Fruit'),
    EmojiData(emoji: '🍅', name: 'Tomato'),
    EmojiData(emoji: '🥥', name: 'Coconut'),
    EmojiData(emoji: '🥑', name: 'Avocado'),
    EmojiData(emoji: '🍆', name: 'Eggplant'),
    EmojiData(emoji: '🥔', name: 'Potato'),
    EmojiData(emoji: '🥕', name: 'Carrot'),
    EmojiData(emoji: '🌽', name: 'Corn'),
    EmojiData(emoji: '🥒', name: 'Cucumber'),
    EmojiData(emoji: '🥬', name: 'Leafy Green'),
    EmojiData(emoji: '🥦', name: 'Broccoli'),
    EmojiData(emoji: '🍞', name: 'Bread'),
    EmojiData(emoji: '🥐', name: 'Croissant'),
    EmojiData(emoji: '🥖', name: 'Baguette Bread'),
    EmojiData(emoji: '🍕', name: 'Pizza'),
    EmojiData(emoji: '🍔', name: 'Hamburger'),
    EmojiData(emoji: '🍟', name: 'French Fries'),
    EmojiData(emoji: '🌭', name: 'Hot Dog'),
    EmojiData(emoji: '🥪', name: 'Sandwich'),
    EmojiData(emoji: '🌮', name: 'Taco'),
    EmojiData(emoji: '🌯', name: 'Burrito'),
    EmojiData(emoji: '🍦', name: 'Soft Ice Cream'),
    EmojiData(emoji: '🍧', name: 'Shaved Ice'),
    EmojiData(emoji: '🍨', name: 'Ice Cream'),
    EmojiData(emoji: '🍩', name: 'Doughnut'),
    EmojiData(emoji: '🍪', name: 'Cookie'),
    EmojiData(emoji: '🎂', name: 'Birthday Cake'),
    EmojiData(emoji: '🍰', name: 'Shortcake'),
    EmojiData(emoji: '🧁', name: 'Cupcake'),
    EmojiData(emoji: '🍫', name: 'Chocolate Bar'),
    EmojiData(emoji: '🍬', name: 'Candy'),
    EmojiData(emoji: '🍭', name: 'Lollipop'),
    EmojiData(emoji: '☕', name: 'Hot Beverage'),
    EmojiData(emoji: '🍵', name: 'Teacup Without Handle'),
    EmojiData(emoji: '🍶', name: 'Sake'),
    EmojiData(emoji: '🍺', name: 'Beer Mug'),
    EmojiData(emoji: '🍻', name: 'Clinking Beer Mugs'),
    EmojiData(emoji: '🍷', name: 'Wine Glass'),
    EmojiData(emoji: '🥤', name: 'Cup with Straw'),
  ];

  // Travel & Places
  static const List<EmojiData> travelAndPlaces = [
    EmojiData(emoji: '🌍', name: 'Globe Showing Europe-Africa'),
    EmojiData(emoji: '🌎', name: 'Globe Showing Americas'),
    EmojiData(emoji: '🌏', name: 'Globe Showing Asia-Australia'),
    EmojiData(emoji: '🌐', name: 'Globe with Meridians'),
    EmojiData(emoji: '🗺️', name: 'World Map'),
    EmojiData(emoji: '🏔️', name: 'Snow-Capped Mountain'),
    EmojiData(emoji: '🏖️', name: 'Beach with Umbrella'),
    EmojiData(emoji: '🏝️', name: 'Desert Island'),
    EmojiData(emoji: '🏠', name: 'House'),
    EmojiData(emoji: '🏡', name: 'House with Garden'),
    EmojiData(emoji: '🏢', name: 'Office Building'),
    EmojiData(emoji: '🏣', name: 'Japanese Post Office'),
    EmojiData(emoji: '🏤', name: 'Post Office'),
    EmojiData(emoji: '🏥', name: 'Hospital'),
    EmojiData(emoji: '🏦', name: 'Bank'),
    EmojiData(emoji: '🏨', name: 'Hotel'),
    EmojiData(emoji: '🏩', name: 'Love Hotel'),
    EmojiData(emoji: '🏪', name: 'Convenience Store'),
    EmojiData(emoji: '🏫', name: 'School'),
    EmojiData(emoji: '🏬', name: 'Department Store'),
    EmojiData(emoji: '🏭', name: 'Factory'),
    EmojiData(emoji: '🏯', name: 'Japanese Castle'),
    EmojiData(emoji: '🏰', name: 'Castle'),
    EmojiData(emoji: '💒', name: 'Wedding'),
    EmojiData(emoji: '🗼', name: 'Tokyo Tower'),
    EmojiData(emoji: '🗽', name: 'Statue of Liberty'),
    EmojiData(emoji: '⛪', name: 'Church'),
    EmojiData(emoji: '🕌', name: 'Mosque'),
    EmojiData(emoji: '🚗', name: 'Automobile'),
    EmojiData(emoji: '🚕', name: 'Taxi'),
    EmojiData(emoji: '🚙', name: 'Sport Utility Vehicle'),
    EmojiData(emoji: '🚌', name: 'Bus'),
    EmojiData(emoji: '🚎', name: 'Trolleybus'),
    EmojiData(emoji: '🚐', name: 'Minibus'),
    EmojiData(emoji: '🚑', name: 'Ambulance'),
    EmojiData(emoji: '🚒', name: 'Fire Engine'),
    EmojiData(emoji: '🚓', name: 'Police Car'),
    EmojiData(emoji: '🚔', name: 'Oncoming Police Car'),
    EmojiData(emoji: '🚚', name: 'Delivery Truck'),
    EmojiData(emoji: '🚛', name: 'Articulated Lorry'),
    EmojiData(emoji: '🚜', name: 'Tractor'),
    EmojiData(emoji: '🚲', name: 'Bicycle'),
    EmojiData(emoji: '✈️', name: 'Airplane'),
    EmojiData(emoji: '🚀', name: 'Rocket'),
    EmojiData(emoji: '🚁', name: 'Helicopter'),
    EmojiData(emoji: '🚢', name: 'Ship'),
    EmojiData(emoji: '⛵', name: 'Sailboat'),
    EmojiData(emoji: '🚤', name: 'Speedboat'),
  ];

  // Objects
  static const List<EmojiData> objects = [
    EmojiData(emoji: '⌚', name: 'Watch'),
    EmojiData(emoji: '📱', name: 'Mobile Phone'),
    EmojiData(emoji: '💻', name: 'Laptop'),
    EmojiData(emoji: '⌨️', name: 'Keyboard'),
    EmojiData(emoji: '🖥️', name: 'Desktop Computer'),
    EmojiData(emoji: '🖨️', name: 'Printer'),
    EmojiData(emoji: '🖱️', name: 'Computer Mouse'),
    EmojiData(emoji: '💾', name: 'Floppy Disk'),
    EmojiData(emoji: '💿', name: 'Optical Disk'),
    EmojiData(emoji: '📀', name: 'DVD'),
    EmojiData(emoji: '📷', name: 'Camera'),
    EmojiData(emoji: '📹', name: 'Video Camera'),
    EmojiData(emoji: '📺', name: 'Television'),
    EmojiData(emoji: '📻', name: 'Radio'),
    EmojiData(emoji: '🎥', name: 'Movie Camera'),
    EmojiData(emoji: '☎️', name: 'Telephone'),
    EmojiData(emoji: '📞', name: 'Telephone Receiver'),
    EmojiData(emoji: '📠', name: 'Fax Machine'),
    EmojiData(emoji: '💡', name: 'Light Bulb'),
    EmojiData(emoji: '🔦', name: 'Flashlight'),
    EmojiData(emoji: '🕯️', name: 'Candle'),
    EmojiData(emoji: '📕', name: 'Closed Book'),
    EmojiData(emoji: '📗', name: 'Green Book'),
    EmojiData(emoji: '📘', name: 'Blue Book'),
    EmojiData(emoji: '📙', name: 'Orange Book'),
    EmojiData(emoji: '📚', name: 'Books'),
    EmojiData(emoji: '📓', name: 'Notebook'),
    EmojiData(emoji: '📖', name: 'Open Book'),
    EmojiData(emoji: '🔒', name: 'Locked'),
    EmojiData(emoji: '🔓', name: 'Unlocked'),
    EmojiData(emoji: '🔑', name: 'Key'),
    EmojiData(emoji: '🔨', name: 'Hammer'),
    EmojiData(emoji: '🔧', name: 'Wrench'),
    EmojiData(emoji: '🔩', name: 'Nut and Bolt'),
    EmojiData(emoji: '⚙️', name: 'Gear'),
    EmojiData(emoji: '💰', name: 'Money Bag'),
    EmojiData(emoji: '💳', name: 'Credit Card'),
    EmojiData(emoji: '💎', name: 'Gem Stone'),
    EmojiData(emoji: '⚖️', name: 'Balance Scale'),
    EmojiData(emoji: '🔬', name: 'Microscope'),
    EmojiData(emoji: '🔭', name: 'Telescope'),
    EmojiData(emoji: '📡', name: 'Satellite Antenna'),
    EmojiData(emoji: '💉', name: 'Syringe'),
    EmojiData(emoji: '💊', name: 'Pill'),
    EmojiData(emoji: '🚪', name: 'Door'),
    EmojiData(emoji: '🛏️', name: 'Bed'),
    EmojiData(emoji: '🚽', name: 'Toilet'),
    EmojiData(emoji: '🚿', name: 'Shower'),
    EmojiData(emoji: '🛁', name: 'Bathtub'),
    EmojiData(emoji: '⏰', name: 'Alarm Clock'),
    EmojiData(emoji: '⏱️', name: 'Stopwatch'),
    EmojiData(emoji: '⏲️', name: 'Timer Clock'),
    EmojiData(emoji: '🎁', name: 'Wrapped Gift'),
    EmojiData(emoji: '🎈', name: 'Balloon'),
    EmojiData(emoji: '🎉', name: 'Party Popper'),
    EmojiData(emoji: '🎊', name: 'Confetti Ball'),
  ];

  // Symbols
  static const List<EmojiData> symbols = [
    EmojiData(emoji: '❤️', name: 'Red Heart'),
    EmojiData(emoji: '🧡', name: 'Orange Heart'),
    EmojiData(emoji: '💛', name: 'Yellow Heart'),
    EmojiData(emoji: '💚', name: 'Green Heart'),
    EmojiData(emoji: '💙', name: 'Blue Heart'),
    EmojiData(emoji: '💜', name: 'Purple Heart'),
    EmojiData(emoji: '🖤', name: 'Black Heart'),
    EmojiData(emoji: '🤍', name: 'White Heart'),
    EmojiData(emoji: '💔', name: 'Broken Heart'),
    EmojiData(emoji: '❣️', name: 'Heart Exclamation'),
    EmojiData(emoji: '💕', name: 'Two Hearts'),
    EmojiData(emoji: '💞', name: 'Revolving Hearts'),
    EmojiData(emoji: '💓', name: 'Beating Heart'),
    EmojiData(emoji: '💗', name: 'Growing Heart'),
    EmojiData(emoji: '💖', name: 'Sparkling Heart'),
    EmojiData(emoji: '💘', name: 'Heart with Arrow'),
    EmojiData(emoji: '💝', name: 'Heart with Ribbon'),
    EmojiData(emoji: '⭐', name: 'Star'),
    EmojiData(emoji: '🌟', name: 'Glowing Star'),
    EmojiData(emoji: '✨', name: 'Sparkles'),
    EmojiData(emoji: '⚡', name: 'High Voltage'),
    EmojiData(emoji: '🔥', name: 'Fire'),
    EmojiData(emoji: '💯', name: 'Hundred Points'),
    EmojiData(emoji: '✅', name: 'Check Mark Button'),
    EmojiData(emoji: '❌', name: 'Cross Mark'),
    EmojiData(emoji: '❓', name: 'Question Mark'),
    EmojiData(emoji: '❗', name: 'Exclamation Mark'),
    EmojiData(emoji: '⚠️', name: 'Warning'),
    EmojiData(emoji: '🔔', name: 'Bell'),
    EmojiData(emoji: '🔕', name: 'Bell with Slash'),
    EmojiData(emoji: '🎵', name: 'Musical Note'),
    EmojiData(emoji: '🎶', name: 'Musical Notes'),
    EmojiData(emoji: '🔊', name: 'Speaker High Volume'),
    EmojiData(emoji: '🔇', name: 'Muted Speaker'),
    EmojiData(emoji: '📢', name: 'Loudspeaker'),
    EmojiData(emoji: '💬', name: 'Speech Balloon'),
    EmojiData(emoji: '💭', name: 'Thought Balloon'),
    EmojiData(emoji: '🕐', name: 'One O\'Clock'),
    EmojiData(emoji: '🕑', name: 'Two O\'Clock'),
    EmojiData(emoji: '🕒', name: 'Three O\'Clock'),
    EmojiData(emoji: '🕓', name: 'Four O\'Clock'),
    EmojiData(emoji: '🕔', name: 'Five O\'Clock'),
    EmojiData(emoji: '🕕', name: 'Six O\'Clock'),
  ];

  // all icons
  static List<EmojiData> get icons => [
    ...animalsAndNature,
    ...foodAndDrink,
    ...travelAndPlaces,
    ...objects,
    ...symbols,
  ];

  // Get
  // static List<EmojiData> icons() {
  //   return [
  //     ...animalsAndNature,
  //     ...foodAndDrink,
  //     ...travelAndPlaces,
  //     ...objects,
  //     ...symbols,
  //   ];
  // }
}

// /// Material Icons organized by category
// class MaterialIconsList {
//   // Communication & Social
//   static const List<IconDataItem> communication = [
//     IconDataItem(icon: Icons.phone, name: 'Phone'),
//     IconDataItem(icon: Icons.email, name: 'Email'),
//     IconDataItem(icon: Icons.message, name: 'Message'),
//     IconDataItem(icon: Icons.chat, name: 'Chat'),
//     IconDataItem(icon: Icons.chat_bubble, name: 'Chat Bubble'),
//     IconDataItem(icon: Icons.forum, name: 'Forum'),
//     IconDataItem(icon: Icons.send, name: 'Send'),
//     IconDataItem(icon: Icons.call, name: 'Call'),
//     IconDataItem(icon: Icons.video_call, name: 'Video Call'),
//     IconDataItem(icon: Icons.contacts, name: 'Contacts'),
//     IconDataItem(icon: Icons.person, name: 'Person'),
//     IconDataItem(icon: Icons.group, name: 'Group'),
//     IconDataItem(icon: Icons.notifications, name: 'Notifications'),
//     IconDataItem(icon: Icons.notifications_active, name: 'Notifications Active'),
//     IconDataItem(icon: Icons.share, name: 'Share'),
//   ];

//   // Media & Content
//   static const List<IconDataItem> media = [
//     IconDataItem(icon: Icons.camera, name: 'Camera'),
//     IconDataItem(icon: Icons.photo, name: 'Photo'),
//     IconDataItem(icon: Icons.image, name: 'Image'),
//     IconDataItem(icon: Icons.photo_library, name: 'Photo Library'),
//     IconDataItem(icon: Icons.video_library, name: 'Video Library'),
//     IconDataItem(icon: Icons.music_note, name: 'Music Note'),
//     IconDataItem(icon: Icons.movie, name: 'Movie'),
//     IconDataItem(icon: Icons.play_arrow, name: 'Play Arrow'),
//     IconDataItem(icon: Icons.pause, name: 'Pause'),
//     IconDataItem(icon: Icons.stop, name: 'Stop'),
//     IconDataItem(icon: Icons.volume_up, name: 'Volume Up'),
//     IconDataItem(icon: Icons.volume_down, name: 'Volume Down'),
//     IconDataItem(icon: Icons.volume_mute, name: 'Volume Mute'),
//     IconDataItem(icon: Icons.mic, name: 'Microphone'),
//     IconDataItem(icon: Icons.videocam, name: 'Video Camera'),
//   ];

//   // Navigation
//   static const List<IconDataItem> navigation = [
//     IconDataItem(icon: Icons.home, name: 'Home'),
//     IconDataItem(icon: Icons.menu, name: 'Menu'),
//     IconDataItem(icon: Icons.arrow_back, name: 'Arrow Back'),
//     IconDataItem(icon: Icons.arrow_forward, name: 'Arrow Forward'),
//     IconDataItem(icon: Icons.arrow_upward, name: 'Arrow Upward'),
//     IconDataItem(icon: Icons.arrow_downward, name: 'Arrow Downward'),
//     IconDataItem(icon: Icons.chevron_left, name: 'Chevron Left'),
//     IconDataItem(icon: Icons.chevron_right, name: 'Chevron Right'),
//     IconDataItem(icon: Icons.expand_more, name: 'Expand More'),
//     IconDataItem(icon: Icons.expand_less, name: 'Expand Less'),
//     IconDataItem(icon: Icons.navigate_next, name: 'Navigate Next'),
//     IconDataItem(icon: Icons.navigate_before, name: 'Navigate Before'),
//     IconDataItem(icon: Icons.close, name: 'Close'),
//     IconDataItem(icon: Icons.more_vert, name: 'More Vertical'),
//     IconDataItem(icon: Icons.more_horiz, name: 'More Horizontal'),
//   ];

//   // Action Icons
//   static const List<IconDataItem> actions = [
//     IconDataItem(icon: Icons.add, name: 'Add'),
//     IconDataItem(icon: Icons.remove, name: 'Remove'),
//     IconDataItem(icon: Icons.edit, name: 'Edit'),
//     IconDataItem(icon: Icons.delete, name: 'Delete'),
//     IconDataItem(icon: Icons.save, name: 'Save'),
//     IconDataItem(icon: Icons.search, name: 'Search'),
//     IconDataItem(icon: Icons.refresh, name: 'Refresh'),
//     IconDataItem(icon: Icons.download, name: 'Download'),
//     IconDataItem(icon: Icons.upload, name: 'Upload'),
//     IconDataItem(icon: Icons.check, name: 'Check'),
//     IconDataItem(icon: Icons.check_circle, name: 'Check Circle'),
//     IconDataItem(icon: Icons.cancel, name: 'Cancel'),
//     IconDataItem(icon: Icons.settings, name: 'Settings'),
//     IconDataItem(icon: Icons.favorite, name: 'Favorite'),
//     IconDataItem(icon: Icons.favorite_border, name: 'Favorite Border'),
//     IconDataItem(icon: Icons.star, name: 'Star'),
//     IconDataItem(icon: Icons.star_border, name: 'Star Border'),
//     IconDataItem(icon: Icons.bookmark, name: 'Bookmark'),
//     IconDataItem(icon: Icons.bookmark_border, name: 'Bookmark Border'),
//   ];

//   // File & Document
//   static const List<IconDataItem> files = [
//     IconDataItem(icon: Icons.folder, name: 'Folder'),
//     IconDataItem(icon: Icons.folder_open, name: 'Folder Open'),
//     IconDataItem(icon: Icons.insert_drive_file, name: 'File'),
//     IconDataItem(icon: Icons.description, name: 'Description'),
//     IconDataItem(icon: Icons.attachment, name: 'Attachment'),
//     IconDataItem(icon: Icons.cloud, name: 'Cloud'),
//     IconDataItem(icon: Icons.cloud_upload, name: 'Cloud Upload'),
//     IconDataItem(icon: Icons.cloud_download, name: 'Cloud Download'),
//     IconDataItem(icon: Icons.archive, name: 'Archive'),
//     IconDataItem(icon: Icons.unarchive, name: 'Unarchive'),
//   ];

//   // Shopping & Commerce
//   static const List<IconDataItem> shopping = [
//     IconDataItem(icon: Icons.shopping_cart, name: 'Shopping Cart'),
//     IconDataItem(icon: Icons.shopping_bag, name: 'Shopping Bag'),
//     IconDataItem(icon: Icons.store, name: 'Store'),
//     IconDataItem(icon: Icons.payment, name: 'Payment'),
//     IconDataItem(icon: Icons.credit_card, name: 'Credit Card'),
//     IconDataItem(icon: Icons.account_balance_wallet, name: 'Wallet'),
//     IconDataItem(icon: Icons.local_offer, name: 'Local Offer'),
//     IconDataItem(icon: Icons.card_giftcard, name: 'Gift Card'),
//   ];

//   // Location & Maps
//   static const List<IconDataItem> location = [
//     IconDataItem(icon: Icons.location_on, name: 'Location On'),
//     IconDataItem(icon: Icons.location_off, name: 'Location Off'),
//     IconDataItem(icon: Icons.my_location, name: 'My Location'),
//     IconDataItem(icon: Icons.map, name: 'Map'),
//     IconDataItem(icon: Icons.directions, name: 'Directions'),
//     IconDataItem(icon: Icons.navigation, name: 'Navigation'),
//     IconDataItem(icon: Icons.place, name: 'Place'),
//     IconDataItem(icon: Icons.near_me, name: 'Near Me'),
//   ];

//   // Time & Date
//   static const List<IconDataItem> time = [
//     IconDataItem(icon: Icons.access_time, name: 'Access Time'),
//     IconDataItem(icon: Icons.alarm, name: 'Alarm'),
//     IconDataItem(icon: Icons.schedule, name: 'Schedule'),
//     IconDataItem(icon: Icons.calendar_today, name: 'Calendar Today'),
//     IconDataItem(icon: Icons.event, name: 'Event'),
//     IconDataItem(icon: Icons.watch_later, name: 'Watch Later'),
//   ];

//   // Weather
//   static const List<IconDataItem> weather = [
//     IconDataItem(icon: Icons.wb_sunny, name: 'Sunny'),
//     IconDataItem(icon: Icons.wb_cloudy, name: 'Cloudy'),
//     IconDataItem(icon: Icons.brightness_2, name: 'Night'),
//     IconDataItem(icon: Icons.brightness_5, name: 'Brightness'),
//   ];

//   // Device & Hardware
//   static const List<IconDataItem> devices = [
//     IconDataItem(icon: Icons.phone_android, name: 'Phone Android'),
//     IconDataItem(icon: Icons.phone_iphone, name: 'Phone iPhone'),
//     IconDataItem(icon: Icons.tablet, name: 'Tablet'),
//     IconDataItem(icon: Icons.laptop, name: 'Laptop'),
//     IconDataItem(icon: Icons.desktop_windows, name: 'Desktop'),
//     IconDataItem(icon: Icons.watch, name: 'Watch'),
//     IconDataItem(icon: Icons.headset, name: 'Headset'),
//     IconDataItem(icon: Icons.keyboard, name: 'Keyboard'),
//     IconDataItem(icon: Icons.mouse, name: 'Mouse'),
//     IconDataItem(icon: Icons.battery_full, name: 'Battery Full'),
//     IconDataItem(icon: Icons.wifi, name: 'WiFi'),
//     IconDataItem(icon: Icons.bluetooth, name: 'Bluetooth'),
//   ];

//   // Security & Privacy
//   static const List<IconDataItem> security = [
//     IconDataItem(icon: Icons.lock, name: 'Lock'),
//     IconDataItem(icon: Icons.lock_open, name: 'Lock Open'),
//     IconDataItem(icon: Icons.vpn_key, name: 'VPN Key'),
//     IconDataItem(icon: Icons.security, name: 'Security'),
//     IconDataItem(icon: Icons.verified_user, name: 'Verified User'),
//     IconDataItem(icon: Icons.visibility, name: 'Visibility'),
//     IconDataItem(icon: Icons.visibility_off, name: 'Visibility Off'),
//   ];

//   // Social & Community
//   static const List<IconDataItem> social = [
//     IconDataItem(icon: Icons.thumb_up, name: 'Thumb Up'),
//     IconDataItem(icon: Icons.thumb_down, name: 'Thumb Down'),
//     IconDataItem(icon: Icons.people, name: 'People'),
//     IconDataItem(icon: Icons.public, name: 'Public'),
//     IconDataItem(icon: Icons.language, name: 'Language'),
//   ];

//   // Status & Alerts
//   static const List<IconDataItem> status = [
//     IconDataItem(icon: Icons.info, name: 'Info'),
//     IconDataItem(icon: Icons.error, name: 'Error'),
//     IconDataItem(icon: Icons.warning, name: 'Warning'),
//     IconDataItem(icon: Icons.help, name: 'Help'),
//     IconDataItem(icon: Icons.done, name: 'Done'),
//     IconDataItem(icon: Icons.done_all, name: 'Done All'),
//   ];

//   // Get all icons
//   static List<IconDataItem> getAllIcons() {
//     return [
//       ...communication,
//       ...media,
//       ...navigation,
//       ...actions,
//       ...files,
//       ...shopping,
//       ...location,
//       ...time,
//       ...weather,
//       ...devices,
//       ...security,
//       ...social,
//       ...status,
//     ];
//   }
// }
